### ISSUE TITLE
Facebook permission popup is not working when adding the "publish_to_groups", "groups_access_member_info" scopes

### ISSUE THREAD

**Issue by hemasharma05** [joelbutcher/laravel-facebook-graph#12]
Facebook permission popup is not working when I am adding the "publish_to_groups","groups_access_member_info" scopes (currently using laravel socialite package.)

For permission popup is working fine for these "pages_show_list","pages_read_engagement","pages_manage_posts","instagram_basic","public_profile","instagram_content_publish". (All permission has been approved by the Facebook).

Why Facebook permission popup is not working with these "publish_to_groups","groups_access_member_info" scopes?

**Comment by joelbutcher** [comment]
@hemasharma05 What's the redirect url being generated?

**Comment by hemasharma05** [comment]
public function redirect(){   
        try {
                return Socialite::driver('facebook')->scopes(["pages_show_list","pages_read_engagement","pages_manage_posts","instagram_basic","public_profile","instagram_content_publish","publish_to_groups","groups_access_member_info"])->with(['auth_type'=>'reauthorize'])->redirect();
            }
        } catch (Exception $e) {
                return redirect('/user/my-info')->with(['error'=> $e->getMessage()]);
        }
}

> @hemasharma05 What's the redirect url being generated?

**Comment by joelbutcher** [comment]
@hemasharma05 you're using socialite, that doesn't interact with this package in anyway. I suggest you raise a PR with them.
