### ISSUE TITLE
Documentation broken

### ISSUE THREAD

**Issue by japafrite** [joelbutcher/laravel-facebook-graph#13]
Hello, 
Links are broken in documentation page here https://github.com/joelbutcher/laravel-facebook-graph/tree/1.x/docs.
I don't understand how to use this package compared to the not laravel one.

**Comment by joelbutcher** [comment]
@japafrite Thanks for the feedback and for pointing this out - It's been something on my todo list for a while. I'll create a new issue for documentation and look at sorting it soon.

For your information however, this package is pretty much just a Service Provide and a Facade to interact with the main Facebook package.

**Comment by joelbutcher** [comment]
There's a demo Laravel project [here](https://github.com/joelbutcher/laravel-facebook-graph-demo-app)

**Comment by japafrite** [comment]
Thank you for your answer, I wil try to use it with your information
