### ISSUE TITLE
Call to undefined method JoelButcher\\Facebook\\Facades\\Facebook::get()

### ISSUE THREAD

**Issue by marvennsuson** [joelbutcher/laravel-facebook-graph#16]
Hello can any one know how to fixed this i already follow the documentation in this Package but i could not resolve this issue
![Screenshot_2022-11-10_12-00-10](https://user-images.githubusercontent.com/58071090/201260580-ce12ab57-a034-48a0-af29-1df337dade17.png)

**Comment by joelbutcher** [comment]
@marvennsuson where's the error originating from. Is this custom code you've written, or code within the library that's failing?

**Comment by marvennsuson** [comment]
I used your Code from documentation

**Comment by joelbutcher** [comment]
@marvennsuson have you registered the packages service provider?
