### ISSUE TITLE
An active access token must be used to query information about the current user.

### ISSUE THREAD

**Issue by msikorski26** [joelbutcher/laravel-facebook-graph#24]
When I try to send a message, I get
"An active access token must be used to query information about the current user."

```
$this->facebook->post(
                '/me/messages',
                [
                    'recipient' => ['id' => $userId],
                    'message' => ['text' => $message],
                ],
                // Page access token
            );
```

**Comment by joelbutcher** [comment]
This message comes directly from Facebook. Please refer to their documentation for more information: https://developers.facebook.com/docs/facebook-login/guides/access-tokens/

**Comment by msikorski26** [comment]
> This message comes directly from Facebook. Please refer to their documentation for more information: https://developers.facebook.com/docs/facebook-login/guides/access-tokens/

I only get such a response when I use the sdk from your repository. When I make a request to the api via e.g. Postman everything works
