### ISSUE TITLE
Error uploading local files to a page

### ISSUE THREAD

**Issue by AstroCorp** [joelbutcher/laravel-facebook-graph#25]
I am trying to upload an image to a facebook page, to get the page token I do this:

```
$response = Facebook::get("/$facebookPageId", [
    'fields' => 'access_token',
    'access_token' => $accessToken,
]);
```
And to publish the photo I do this:

```
$file = new FacebookFile($path);

$response = Facebook::post("/$pageId/photos", [
    'access_token' => $pageToken,
    'source' => $file,
    'published' => true,
]);
```

This returns this error:

`(#100) 0 does not resolve to a valid user ID`

```
Facebook API: v20
"joelbutcher/laravel-facebook-graph": "^1.3",
```

Previously this worked, I don't see any changes in the facebook changelog that modifies to this.

**Comment by joelbutcher** [comment]
The last commit to this package that changed anything to do with Facebook was over a year ago. If something's changed in that time frame, it's not to do with this package.
